### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by aleksazr** [luihabl/rect_pack.h#1]
Hi,

Let's say you have just two rects, dimensions 900x900 and 1100x1100,
and you call rect_pack(1000,1000, true, rects, 2)

The first rect can fit, but the second can't, paging enabled or not.
But, with paging enabled, rect_pack will successfully pack the second rect.

The bug is in pack_bin_tree():

    pack_res res;
    res.all_fit = true;
    res.none_fit = true;

    rect_r* r = ctx->r;

    if(ctx->next == ctx->last) {
        // here, you don't check if it will actually fit
        r[ctx->next].info = empty_rect_r();
        r[ctx->next].info.packed = true;
        r[ctx->next].info.page = ctx->page;
        return res;
    }

Also, **ctx.paging** is not actually used anywhere.

**Comment by luihabl** [comment]
Hi @aleksazr, thanks! I'll have a look

**Comment by luihabl** [comment]
Solved in 4bfc542.
