### ISSUE TITLE
BUG report #2

### ISSUE THREAD

**Issue by aleksazr** [luihabl/rect_pack.h#2]
#define nrects 6
    static rect_r rects[nrects] = {
      {.id = 0, .w = 5, .h = 6},
      {.id = 1, .w = 5, .h = 5},
      {.id = 2, .w = 2, .h = 5},
      {.id = 3, .w = 4, .h = 6},
      {.id = 4, .w = 7, .h = 1},
      {.id = 5, .w = 2, .h = 7},
    };

    bool b = rect_pack(10, 10, true, rects, nrects);
    if (b == false) STOP;

6 rects with dimensions less than 10x10, can't be packed to 10x10 with paging enabled.

**Comment by luihabl** [comment]
Solved in 4bfc542.
